"""Shared constants for AWF validation worktree reason codes."""

from __future__ import annotations

VALIDATION_WORKTREE_CLEANUP_FAILED = "VALIDATION_WORKTREE_CLEANUP_FAILED"
VALIDATION_WORKTREE_PRE_EXISTING_DIRTY = "VALIDATION_WORKTREE_PRE_EXISTING_DIRTY"
VALIDATION_WORKTREE_SIDE_EFFECTS_CLEANED = "VALIDATION_WORKTREE_SIDE_EFFECTS_CLEANED"
VALIDATION_WORKTREE_STATUS_FAILED = "VALIDATION_WORKTREE_STATUS_FAILED"
VALIDATION_INFRASTRUCTURE_ERROR = "VALIDATION_INFRASTRUCTURE_ERROR"
