"""Compatibility wrapper for validation commands targeting the legacy path."""

from tests.unit.api import test_operations_listing as _operations_listing

session = _operations_listing.session
sample_data = _operations_listing.sample_data

test_get_operation_not_found = _operations_listing.test_get_operation_not_found
test_operation_response_derives_pr_monitor_recovery_fields = (
    _operations_listing.test_operation_response_derives_pr_monitor_recovery_fields
)
test_list_operations_empty = _operations_listing.test_list_operations_empty
test_list_operations_global = _operations_listing.test_list_operations_global
test_list_operations_limit_validation = _operations_listing.test_list_operations_limit_validation
test_list_operations_ordering = _operations_listing.test_list_operations_ordering
test_list_workspace_operations_filters = _operations_listing.test_list_workspace_operations_filters
test_list_workspace_operations_not_found = (
    _operations_listing.test_list_workspace_operations_not_found
)
authed_client = _operations_listing.authed_client
