"""Host setup contracts for AWF first-run flows."""

from awf.host_setup.config import (
    DEFAULT_API_HOST_PORT,
    DEFAULT_HOST_SETUP_WORK_DIR,
    DEFAULT_INSTALL_CHANNEL,
    HOST_SETUP_CONFIG_CORRUPT,
    HOST_SETUP_CONFIG_SECRET_VALUE,
    HOST_SETUP_CONFIG_VERSION,
    ApiConfig,
    ClientIntegrationConfig,
    ConsentConfig,
    HostSetupConfig,
    HostSetupConfigError,
    InstallConfig,
    ProviderConfig,
    default_host_setup_config_path,
    read_host_setup_config,
    write_host_setup_config,
)
from awf.host_setup.source_assets import (
    SOURCE_CHECKOUT_ASSETS_STALE,
    SOURCE_CHECKOUT_INVALID,
    SOURCE_CHECKOUT_MARKERS,
    SOURCE_CHECKOUT_REQUIRED_MARKER_PATHS,
    SourceCheckoutAssetMetadata,
    SourceCheckoutAssetPaths,
    SourceCheckoutError,
    SourceCheckoutMarker,
    VerifiedSourceCheckout,
    validate_source_checkout,
    verified_source_from_metadata,
)

__all__ = [
    "DEFAULT_API_HOST_PORT",
    "DEFAULT_HOST_SETUP_WORK_DIR",
    "DEFAULT_INSTALL_CHANNEL",
    "HOST_SETUP_CONFIG_CORRUPT",
    "HOST_SETUP_CONFIG_SECRET_VALUE",
    "HOST_SETUP_CONFIG_VERSION",
    "SOURCE_CHECKOUT_ASSETS_STALE",
    "SOURCE_CHECKOUT_INVALID",
    "SOURCE_CHECKOUT_MARKERS",
    "SOURCE_CHECKOUT_REQUIRED_MARKER_PATHS",
    "ApiConfig",
    "ClientIntegrationConfig",
    "ConsentConfig",
    "HostSetupConfig",
    "HostSetupConfigError",
    "InstallConfig",
    "ProviderConfig",
    "SourceCheckoutAssetMetadata",
    "SourceCheckoutAssetPaths",
    "SourceCheckoutError",
    "SourceCheckoutMarker",
    "VerifiedSourceCheckout",
    "default_host_setup_config_path",
    "read_host_setup_config",
    "validate_source_checkout",
    "verified_source_from_metadata",
    "write_host_setup_config",
]
