"""initial workspaces operations events

Revision ID: 135102b9a037
Revises:
Create Date: 2026-04-21 21:16:06.601566+00:00

"""
from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op



revision: str = '135102b9a037'
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('workspaces',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('repo_url', sa.String(length=512), nullable=False),
    sa.Column('branch_base', sa.String(length=256), nullable=False),
    sa.Column('branch_name', sa.String(length=256), nullable=True),
    sa.Column('base_commit', sa.String(length=64), nullable=True),
    sa.Column('task_title', sa.String(length=512), nullable=False),
    sa.Column('task_prompt', sa.String(length=16384), nullable=False),
    sa.Column('task_external_id', sa.String(length=128), nullable=True),
    sa.Column('agent', sa.String(length=32), nullable=False),
    sa.Column('env_profile', sa.String(length=128), nullable=True),
    sa.Column('test_commands', sa.JSON(), nullable=False),
    sa.Column('requires_database', sa.Boolean(), nullable=False),
    sa.Column('node_id', sa.String(length=64), nullable=True),
    sa.Column('compose_project_name', sa.String(length=128), nullable=True),
    sa.Column('pr_url', sa.String(length=512), nullable=True),
    sa.Column('failure_reason', sa.String(length=64), nullable=True),
    sa.Column('failure_message', sa.String(length=2048), nullable=True),
    sa.Column('idempotency_key', sa.String(length=128), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('idempotency_key', name='uq_workspaces_idempotency_key')
    )
    op.create_index('ix_workspaces_created_at', 'workspaces', ['created_at'], unique=False)
    op.create_index('ix_workspaces_status', 'workspaces', ['status'], unique=False)
    op.create_table('operations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('workspace_id', sa.String(length=36), nullable=False),
    sa.Column('type', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('error_code', sa.String(length=64), nullable=True),
    sa.Column('error_message', sa.String(length=2048), nullable=True),
    sa.Column('payload', sa.JSON(), nullable=True),
    sa.Column('result', sa.JSON(), nullable=True),
    sa.Column('idempotency_key', sa.String(length=128), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_operations_status', 'operations', ['status'], unique=False)
    op.create_index('ix_operations_workspace', 'operations', ['workspace_id'], unique=False)
    op.create_table('workspace_events',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('workspace_id', sa.String(length=36), nullable=False),
    sa.Column('event_type', sa.String(length=64), nullable=False),
    sa.Column('old_state', sa.String(length=32), nullable=True),
    sa.Column('new_state', sa.String(length=32), nullable=True),
    sa.Column('reason_code', sa.String(length=64), nullable=True),
    sa.Column('payload', sa.JSON(), nullable=True),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_workspace_events_occurred_at', 'workspace_events', ['occurred_at'], unique=False)
    op.create_index('ix_workspace_events_workspace', 'workspace_events', ['workspace_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_workspace_events_workspace', table_name='workspace_events')
    op.drop_index('ix_workspace_events_occurred_at', table_name='workspace_events')
    op.drop_table('workspace_events')
    op.drop_index('ix_operations_workspace', table_name='operations')
    op.drop_index('ix_operations_status', table_name='operations')
    op.drop_table('operations')
    op.drop_index('ix_workspaces_status', table_name='workspaces')
    op.drop_index('ix_workspaces_created_at', table_name='workspaces')
    op.drop_table('workspaces')
    # ### end Alembic commands ###
