"""add index on operations type

Revision ID: 9fe4720d0ffa
Revises: d4e5f6a1b2c3
Create Date: 2026-04-25 11:27:47.366789+00:00

"""
from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op



revision: str = '9fe4720d0ffa'
down_revision: str | Sequence[str] | None = 'd4e5f6a1b2c3'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_operations_type', 'operations', ['type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_operations_type', table_name='operations')
    # ### end Alembic commands ###
