"""stale_reason

Revision ID: ab0b071760d1
Revises: c4d5e6f7a8b9
Create Date: 2026-04-26 16:25:46.434390+00:00

"""
from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op



revision: str = 'ab0b071760d1'
down_revision: str | Sequence[str] | None = 'c4d5e6f7a8b9'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('merge_candidates', sa.Column('stale_reason', sa.String(length=128), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('merge_candidates', 'stale_reason')
    # ### end Alembic commands ###
