"""Add retry_count to validation_runs

Revision ID: ec041f62c7fc
Revises: b9c0d1e2f3a4
Create Date: 2026-04-26 19:59:24.126532+00:00

"""
from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op



revision: str = 'ec041f62c7fc'
down_revision: str | Sequence[str] | None = 'b9c0d1e2f3a4'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('validation_runs', sa.Column('retry_count', sa.Integer(), server_default=sa.text('0'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('validation_runs', 'retry_count')
    # ### end Alembic commands ###
