"""Preserved active execution recovery facade."""

from __future__ import annotations

from awf.control.worker.recovery_preserved_flow import (
    _attach_preserved_active_pr_monitor,
    _cancel_superseded_active_execution_operations,
    _create_preserved_active_replacement,
    _record_preserved_active_execution_after_restart,
    _record_preserved_active_operator_required,
    _record_preserved_active_salvage_blocked,
    _record_preserved_active_salvage_not_possible,
    _recover_preserved_active_execution,
    _request_preserved_active_validation,
)
from awf.control.worker.recovery_preserved_queries import (
    _active_execution_preservation_event_floor,
    _active_execution_preservation_is_expired,
    _active_execution_preservation_salvage_event_floor,
    _classify_preserved_active_worktree,
    _has_active_preserved_validation_recovery,
    _has_current_preserved_active_execution,
    _has_current_salvage_event,
    _has_expired_preserved_active_execution,
    _has_operator_refresh_after_latest_preservation,
    _has_operator_refresh_after_latest_preservation_for_workspace,
    _has_preserved_active_execution_event,
    _latest_current_salvage_blocked_reason,
    _latest_operator_refresh_requested_at,
    _latest_preserved_active_execution_at,
    _latest_preserved_active_execution_event,
    _preserved_active_worktree_path,
    _resolve_preserved_active_branch_open_pr,
    _run_preserved_active_git,
)

__all__ = (
    "_recover_preserved_active_execution",
    "_record_preserved_active_execution_after_restart",
    "_attach_preserved_active_pr_monitor",
    "_request_preserved_active_validation",
    "_cancel_superseded_active_execution_operations",
    "_create_preserved_active_replacement",
    "_record_preserved_active_operator_required",
    "_record_preserved_active_salvage_not_possible",
    "_record_preserved_active_salvage_blocked",
    "_has_operator_refresh_after_latest_preservation",
    "_has_operator_refresh_after_latest_preservation_for_workspace",
    "_has_current_preserved_active_execution",
    "_has_expired_preserved_active_execution",
    "_active_execution_preservation_is_expired",
    "_has_preserved_active_execution_event",
    "_latest_preserved_active_execution_at",
    "_latest_preserved_active_execution_event",
    "_has_current_salvage_event",
    "_latest_current_salvage_blocked_reason",
    "_has_active_preserved_validation_recovery",
    "_latest_operator_refresh_requested_at",
    "_active_execution_preservation_event_floor",
    "_active_execution_preservation_salvage_event_floor",
    "_resolve_preserved_active_branch_open_pr",
    "_classify_preserved_active_worktree",
    "_preserved_active_worktree_path",
    "_run_preserved_active_git",
)
